server.servlet.context-path=/post
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5436/yourband_post_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=280000

# be-band para obtener las bandas seguidas por el usuario
services.band.url=http://localhost:8083/band
services.notification.url=http://localhost:8085/notification

management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
